### ISSUE TITLE
awsctx is requiring setup at first run even with a pre-existing $HOME/.aws/config file

### ISSUE THREAD

**Issue by fandujar** [DiTo04/awsctx#1]
I just installed awsctx and expected that it would load my aws/config file that was already there, but instead it asked me to run setup command.

**Comment by davidtennander-instantor** [comment]
Thank you for installing awsctx! 
Aswctx requires setup because otherwise it would not know what to name your current profile. It will not override your current config file, but instead load that as well. 
Do you think this can be more explicitly said in the help command/readme?

**Comment by dtennander** [comment]
Thank you for installing awsctx!
Aswctx requires setup because otherwise it would not know what to name your current profile. It will not override your current config file, but instead load that as well.
Do you think this can be more explicitly said in the help command/readme?

**Comment by weisjohn** [comment]
This is confusing to me as well. I already have multiple profiles in my config file, so why do I need to tell awsctx which ones they are?

**Comment by dtennander** [comment]
I agree that we should improve this!

The problem is that by default your current profile does not have a name.  So what should awsctx call it?
We could solve this by naming it "default". The only problem is that awsctx internally works by changing the name of the chosen profile to `default` which makes "default" a weird name to allow for a profile.

Internally we could solve this by making the "default" profile shown in awsctx be named `awsctx-default` in the `.aws/config` file. But this could create confusion if someone wants to edit their `.aws/config` file by hand after using `awsctx`.

Thoughts?

**Comment by dtennander** [comment]
@weisjohn The only naming that needs to be done is to name the current profile you call "default" before use started using `awsctx`
